#!/usr/bin/env python3
"""
Generate idempotent 19_seed_dish_images.sql from dish_reference.sql (HeidiSQL dump).

- One cover image per dish, matching dishes.ImageUrl in the dump.
- DELETE existing dish_images for mapped dishes before INSERT (no duplicate rows on re-run).
- INSERT IGNORE media_files by (Bucket, ObjectName).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DUMP = ROOT / "SmartLunch-Backend-Service-Infrastructure/Data/Scripts/reference/dish_reference.sql"
OUTPUT = ROOT / "SmartLunch-Backend-Service-Infrastructure/Data/Scripts/04_seed_data/19_seed_dish_images.sql"
BUCKET = "69bfa6de000fdacda87d"


def sql_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def tokenize_sql_tuple(inner: str) -> list[str | None]:
    """Parse SQL VALUES tuple into fields (strings or NULL)."""
    fields: list[str | None] = []
    i = 0
    n = len(inner)

    while i < n:
        while i < n and inner[i] in " \t\r\n":
            i += 1
        if i >= n:
            break
        if i < n - 1 and inner[i : i + 4].upper() == "NULL":
            fields.append(None)
            i += 4
            while i < n and inner[i] in " \t\r\n":
                i += 1
            if i < n and inner[i] == ",":
                i += 1
            continue
        if inner[i] == "'":
            i += 1
            buf: list[str] = []
            while i < n:
                ch = inner[i]
                if ch == "'":
                    if i + 1 < n and inner[i + 1] == "'":
                        buf.append("'")
                        i += 2
                        continue
                    i += 1
                    break
                if ch == "\\":
                    if i + 1 < n:
                        buf.append(inner[i + 1])
                        i += 2
                        continue
                buf.append(ch)
                i += 1
            fields.append("".join(buf))
            while i < n and inner[i] in " \t\r\n":
                i += 1
            if i < n and inner[i] == ",":
                i += 1
            continue
        # unquoted token (number)
        start = i
        while i < n and inner[i] not in ",":
            i += 1
        fields.append(inner[start:i].strip())
        if i < n and inner[i] == ",":
            i += 1

    return fields


def parse_dishes_from_dump(text: str) -> list[dict]:
    rows: list[dict] = []
    in_insert = False
    insert_re = re.compile(r"INSERT\s+INTO\s+`?dishes`?", re.I)

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if insert_re.search(line) and "VALUES" in line.upper():
            in_insert = True
            continue
        if in_insert:
            if line.startswith("--") or line.startswith("/*"):
                continue
            if not line.startswith("("):
                if line.endswith(";"):
                    in_insert = False
                continue
            body = line.rstrip(",").rstrip(";")
            if not body.startswith("("):
                continue
            if not body.endswith(")"):
                continue
            parts = tokenize_sql_tuple(body[1:-1])
            if len(parts) < 8:
                continue
            dish_id = int(str(parts[0]))
            name = parts[2]
            image_url = parts[7]
            if not name:
                continue
            if image_url is not None and str(image_url).upper() == "NULL":
                image_url = None
            if image_url is not None:
                image_url = str(image_url).strip() or None
            rows.append({"id": dish_id, "name": name, "imageUrl": image_url})

    return rows


def owner_user_expr(object_name: str) -> str:
    if object_name.startswith("users/"):
        # users/2/dish-image/...
        parts = object_name.split("/")
        if len(parts) >= 2 and parts[1].isdigit():
            return f"(SELECT Id FROM users WHERE Id = {parts[1]} LIMIT 1)"
    return "(SELECT Id FROM users WHERE Username = 'admin' LIMIT 1)"


def content_type_for(object_name: str) -> str:
    lower = object_name.lower()
    if lower.endswith(".webp"):
        return "image/webp"
    if lower.endswith(".png"):
        return "image/png"
    return "image/jpeg"


def generate_sql(dishes: list[dict]) -> str:
    mapped = [d for d in dishes if d.get("imageUrl")]
    object_names = sorted({d["imageUrl"] for d in mapped})

    lines: list[str] = [
        "-- =====================================================",
        "-- Seed: Dish images (idempotent) — sync from dish_reference.sql",
        "-- Auto-generated by scratch/generate_dish_image_seed_from_dump.py",
        "-- Mỗi món: 1 ảnh cover = dishes.ImageUrl trong dump (không nhân gallery khi chạy lại).",
        "-- =====================================================",
        "",
        "USE SmartLunch;",
        "",
        "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;",
        f"SET @bucket := '{BUCKET}';",
        "",
        "-- 1) Cập nhật ImageUrl trên dishes theo dump (theo tên món, ổn định khi Id thay đổi)",
    ]

    for d in mapped:
        url = sql_escape(d["imageUrl"])
        name = sql_escape(d["name"])
        lines.append(
            f"UPDATE dishes SET ImageUrl = '{url}' WHERE Name COLLATE utf8mb4_unicode_ci = '{name}' COLLATE utf8mb4_unicode_ci LIMIT 1;"
        )

    lines.extend(
        [
            "",
            "-- 2) Xóa toàn bộ liên kết ảnh cũ của các món có ImageUrl (tránh nhân bản khi seed lại)",
            "DELETE di FROM dish_images di",
            "INNER JOIN dishes d ON d.Id = di.DishId",
            "WHERE d.ImageUrl IS NOT NULL AND TRIM(d.ImageUrl) <> '';",
            "",
            "-- 3) media_files (INSERT IGNORE theo Bucket + ObjectName)",
            "INSERT IGNORE INTO media_files (OwnerUserId, Bucket, ObjectName, OriginalFileName, ContentType, SizeBytes, MediaType, IsPublic)",
            "SELECT * FROM (",
        ]
    )

    media_selects = []
    for obj in object_names:
        owner = owner_user_expr(obj)
        ctype = content_type_for(obj)
        orig = sql_escape(Path(obj).name)
        obj_esc = sql_escape(obj)
        media_selects.append(
            f"    SELECT {owner} AS OwnerUserId, @bucket AS Bucket, "
            f"'{obj_esc}' AS ObjectName, '{orig}' AS OriginalFileName, "
            f"'{ctype}' AS ContentType, 0 AS SizeBytes, 'image' AS MediaType, 1 AS IsPublic"
        )

    lines.append("\nUNION ALL\n".join(media_selects))
    lines.append(") AS seed_media;")
    lines.append("")
    lines.append("-- 4) dish_images — mỗi món một cover (SortOrder 0)")

    for d in mapped:
        name = sql_escape(d["name"])
        obj = sql_escape(d["imageUrl"])
        lines.append(
            "INSERT INTO dish_images (DishId, MediaFileId, Role, SortOrder)"
            f" SELECT d.Id, mf.Id, 'cover', 0"
            f" FROM dishes d"
            f" INNER JOIN media_files mf ON mf.Bucket = @bucket AND mf.ObjectName = '{obj}'"
            f" WHERE d.Name COLLATE utf8mb4_unicode_ci = '{name}' COLLATE utf8mb4_unicode_ci"
            f" LIMIT 1;"
        )

    lines.append("")
    lines.append("SELECT CONCAT('Synced ', COUNT(*), ' dish cover image(s).') AS Status")
    lines.append("FROM dish_images WHERE Role = 'cover' AND SortOrder = 0;")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_DUMP,
        help="Path to dish_reference.sql (HeidiSQL dump)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help="Output seed SQL path",
    )
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Input not found: {args.input}", file=sys.stderr)
        return 1

    text = args.input.read_text(encoding="utf-8")
    dishes = parse_dishes_from_dump(text)
    if not dishes:
        print("No dishes parsed from dump.", file=sys.stderr)
        return 1

    with_image = sum(1 for d in dishes if d.get("imageUrl"))
    sql = generate_sql(dishes)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    print(f"Parsed {len(dishes)} dishes ({with_image} with ImageUrl)")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
