#!/usr/bin/env python3
"""
DEPRECATED — use generate_dish_image_seed_from_dump.py instead.

Legacy generator from dish_image_upload_results.json (multi gallery, dễ nhân ảnh khi chạy lại).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS_FILE = ROOT / "scratch/dish_image_upload_results.json"
SQL_FILE = ROOT / "SmartLunch-Backend-Service-Infrastructure/Data/Scripts/04_seed_data/19_seed_dish_images.sql"


def main() -> int:
    if not RESULTS_FILE.exists():
        print(f"Results file not found: {RESULTS_FILE}", file=sys.stderr)
        return 1

    with RESULTS_FILE.open(encoding="utf-8") as f:
        results = json.load(f)

    sql_lines = [
        "-- =====================================================",
        "-- Seed: Dish cover & gallery images (media_files + dish_images)",
        "-- Auto-generated by scratch/generate_image_sql.py based on",
        "-- uploaded Appwrite assets in scratch/dish_image_upload_results.json.",
        "-- =====================================================",
        "",
        "SET @bucket := '69bfa6de000fdacda87d';",
        "",
        "-- 1. Insert records into media_files",
        "INSERT IGNORE INTO media_files (OwnerUserId, Bucket, ObjectName, OriginalFileName, ContentType, SizeBytes, MediaType, IsPublic)",
        "SELECT u.Id, @bucket, v.ObjectName, v.OriginalFileName, 'image/jpeg', v.SizeBytes, 'image', 1",
        "FROM users u",
        "CROSS JOIN ("
    ]

    # Add all unique uploaded objects
    union_lines = []
    for item in results:
        object_name = item["objectName"]
        original_name = Path(object_name).name
        size = item["sizeBytes"]
        union_lines.append(f"    SELECT '{object_name}' AS ObjectName, '{original_name}' AS OriginalFileName, {size} AS SizeBytes")

    sql_lines.append(" UNION ALL\n".join(union_lines))
    sql_lines.append(") AS v")
    sql_lines.append("WHERE u.Username = 'admin';")
    sql_lines.append("")
    sql_lines.append("-- 2. Map media_files to dishes (dish_images)")
    sql_lines.append("DELETE FROM dish_images WHERE MediaFileId IN (")
    sql_lines.append("    SELECT Id FROM media_files WHERE ObjectName LIKE 'dishes/seed/%'")
    sql_lines.append(");")
    sql_lines.append("")

    # Insert mapping for each record
    for item in results:
        dish_name = item["name"].replace("'", "''")  # Escape single quotes
        object_name = item["objectName"]
        img_idx = item["imgIndex"]
        role = "cover" if img_idx == 0 else "gallery"
        sort_order = img_idx
        
        sql_lines.append(
            f"INSERT IGNORE INTO dish_images (DishId, MediaFileId, Role, SortOrder) "
            f"SELECT (SELECT Id FROM dishes WHERE Name = '{dish_name}' LIMIT 1), "
            f"(SELECT Id FROM media_files WHERE ObjectName = '{object_name}' LIMIT 1), "
            f"'{role}', {sort_order};"
        )

    sql_lines.extend(
        [
            "",
            "-- 3. Sync dishes.ImageUrl = Appwrite object key (cover image)",
            "UPDATE dishes d",
            "INNER JOIN dish_images di ON di.DishId = d.Id AND di.Role = 'cover' AND di.SortOrder = 0",
            "INNER JOIN media_files mf ON mf.Id = di.MediaFileId",
            "SET d.ImageUrl = mf.ObjectName",
            "WHERE mf.ObjectName LIKE 'dishes/seed/%';",
            "",
        ]
    )

    SQL_FILE.write_text("\n".join(sql_lines) + "\n", encoding="utf-8")
    print(f"Generated SQL seed file: {SQL_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
