<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt">
      <Version>8.17.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\" />
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\" />
    <Folder Include="Areas\Manager\Controllers\" />
    <Folder Include="Areas\Manager\Data\" />
    <Folder Include="Areas\Manager\Models\" />
    <Folder Include="Areas\Manager\Views\" />
  </ItemGroup>

</Project>
